[FEATURE] subtask - Make context implicit
MoBagel/decanter-ai-core-sdk pull request #16
Opened 2020-09-11 03:42 UTC by MatthewK3023

2020-09-11 05:45 UTC, NoctisHong requested changes
After making Context implicit, you need to update all example files.

2020-09-11 05:52 UTC, NoctisHong requested changes
After making Context implicit, you also need to integrate the doc of Context to Client

2020-09-14 06:15 UTC, schwannden commented on examples/jupyter_example.ipynb
> +    "### Create Decanter Core Client\n",
why is there a \n here?

2020-09-14 06:19 UTC, schwannden commented on examples/example.py
> +    client = core.CoreClient()
no need to add create method, just supply username, password, host as construct parameter here, and connect and create context in class constructor

2020-09-15 10:16 UTC, schwannden submitted a review, later dismissed

2020-09-17 07:06 UTC, NoctisHong submitted a review, later dismissed

2020-09-18 05:10 UTC, NoctisHong approved these changes

2020-09-18 05:10 UTC, merged