Feature/upload task block
MoBagel/decanter-ai-core-sdk pull request #18
Opened 2020-09-15 06:46 UTC by MatthewK3023

this PR is to fix the subtask "Upload Job need to block Setup Job"
https://www.notion.so/51c73a064a244f7dbcb4abeb12a268f7?v=3d8bfc9cbca44349924fc533dc6d4d61&p=04962dc793d147e58d90ec8470aaaa8e

2020-09-17 07:13 UTC, NoctisHong requested changes
Review data_setup

2020-09-18 05:23 UTC, MatthewK3023 commented on src/decanter/core/jobs/data_setup.py
> +attribute.
done

2020-09-18 05:23 UTC, MatthewK3023 commented on src/decanter/core/jobs/data_setup.py
> +    Decanter Core server Stores the upload results in DataUpload attributes.
done

2020-09-18 05:23 UTC, MatthewK3023 commented on src/decanter/core/jobs/data_setup.py
> +    Decanter Core server Stores the upload results in DataUpload attributes.
done

2020-09-18 05:23 UTC, MatthewK3023 commented on src/decanter/core/jobs/data_setup.py
> +        """DataUpload Init.
done

2020-09-18 05:23 UTC, MatthewK3023 commented on src/decanter/core/jobs/data_setup.py
> +class DataSetup(Job):
done

2020-09-18 05:23 UTC, MatthewK3023 commented on src/decanter/core/jobs/data_setup.py
> +        super().__init__(jobs=[train_data],
done

2020-09-18 05:42 UTC, NoctisHong commented on src/decanter/core/jobs/experiment.py
> +            jobs=[train_input.data, train_input.data.jobs[0]]
After adding the correct dependency between DataSetup and DataUpload jobs,
Experiment job will have the denpendency of corresponded data.
So threre should be no changes hrere.

2020-09-18 05:43 UTC, NoctisHong approved these changes

2020-09-18 05:43 UTC, merged